// This fix was generated by Grok (xAI)
// PR submitted by human Spencer Hill (@s3w47m88)
// Root cause identified through collaborative debugging with Grok
// Date: April 13, 2026
import { describe, expect, it, vi } from "vitest";
import { GrokClient } from "./client.js";

describe("GrokClient model fallback behavior", () => {
  it("keeps the selected model when tools are disabled", () => {
    const client = new GrokClient("test-key", "grok-code-fast-1");
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});

    const resolved = (client as any).resolveRequestModel(
      "grok-code-fast-1",
      false
    );

    expect(resolved).toBe("grok-code-fast-1");
    expect(warnSpy).not.toHaveBeenCalled();
  });

  it("falls back once for tool-enabled requests", () => {
    const client = new GrokClient("test-key", "grok-code-fast-1");
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});

    const resolved = (client as any).resolveRequestModel(
      "grok-code-fast-1",
      true
    );

    expect(resolved).toBe("grok-4-1-fast-reasoning");
    expect(warnSpy).toHaveBeenCalledTimes(1);
  });
});
