// This fix was generated by Grok (xAI)
// PR submitted by human Spencer Hill (@s3w47m88)
// Root cause identified through collaborative debugging with Grok
// Date: April 13, 2026
import { describe, expect, it, vi } from "vitest";
import { GrokAgent } from "./grok-agent.js";

describe("GrokAgent runaway loop guards", () => {
  it("uses safer interactive defaults", () => {
    const agent = new GrokAgent("test-key");
    expect(agent.getRuntimeConfig()).toMatchObject({
      toolsEnabled: true,
      chatOnly: false,
      maxToolRounds: 8,
    });
  });

  it("bypasses tools for a short greeting", async () => {
    const agent = new GrokAgent("test-key");
    const chatSpy = vi
      .spyOn((agent as any).grokClient, "chat")
      .mockResolvedValue({ choices: [] });

    const entries = await agent.processUserMessage("Hi.");

    expect(chatSpy).not.toHaveBeenCalled();
    expect(entries.at(-1)?.content).toBe("Hi! What do you need?");
  });

  it("supports chat-only mode", () => {
    const agent = new GrokAgent("test-key", undefined, "grok-code-fast-1", {
      chatOnly: true,
      toolsEnabled: false,
      maxToolRounds: 3,
    });

    expect(agent.getRuntimeConfig()).toMatchObject({
      chatOnly: true,
      toolsEnabled: false,
      maxToolRounds: 3,
      model: "grok-code-fast-1",
    });
  });
});
